config/routes.rb
Rails.application.routes.draw do

  resources :leads

  root 'home#index'

  get ':id' => 'pages#show'

end

app/models/lead.rb
class Lead < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:type].present? && params[:type] == "request_info"
      begin
        LeadNotifier.request_info_email({name: params[:name], email: params[:email], phone: params[:phone]}).deliver
      rescue
      end
    end
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  respond_to :html, :xml, :json
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  def index
    @leads = Lead.all
    respond_with(@leads)
  end

  def show
    respond_with(@lead)
  end

  def new
    @lead = Lead.new
    respond_with(@lead)
  end

  def edit
  end

  def create
    @lead = Lead.new(lead_params)
    if @lead.save
      begin
        LeadNotifier.lead_email(@lead).deliver
      rescue
      end
    else
      render :action => 'new'
    end
    respond_with(@lead)
  end

  def update
    @lead.update(lead_params)
    respond_with(@lead)
  end

  def destroy
    @lead.destroy
    respond_with(@lead)
  end

  private
    def set_lead
      @lead = Lead.find(params[:id])
    end

    def lead_params
      params.require(:lead).permit(:name, :objective, :activities, :pricepoint, :email, :startdate, :location)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    page = params[:id]
    render page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/_howitworks.html.haml
.secondary#learn
  .container
    %h2.title
      %span How It Works
    .feature.row.first
      .col-md-6
        %h3 1. Tell us your fitness goals
        %p Mighty has certified trainers and coaches ready to help you meet your goals. Whether you're just beginning to work out or running a long race, Mighty can help.
        %p Your fitness goals are used to provide service personalized to meet your needs.
      .col-md-6.text-center.feature-icon
        = image_tag("icon-goals.png")
    .feature.row
      .col-md-6.col-md-push-6
        %h3 2. Meet your fitness coach
        %p Mighty curates its list of thousands of highly-experienced trainers to match you to a professional with the background and qualifications best suited to you.
        %p In under 24 hours, Mighty will reach out to you to introduce your personal fitness coach.
      .col-md-6.text-center.feature-icon.col-md-pull-6
        = image_tag("icon-filter.png")
    .feature.row.last
      .col-md-6
        %h3 3. Enjoy your new, healthier lifestyle
        %p Your trainer will schedule a time and location convenient for you where you can meet and begin achieving your goals.
        %p Whether you plan on an individual session or multiple, Mighty and your trainer will help you set up a schedule and routine that you can stick to.
      .col-md-6.text-center.feature-icon
        = image_tag("icon-healthy.png")

app/views/home/_slider.html.haml
.slider-cont
  .slide-wrap
    .slide-strip
      .slide.objective.current
        .panel.lead-form
          .panel-heading
            %h4 Ready to find your coach?
            %p
              Tell us what you'd like to work on.
              %br.visible-xs
              %strong Your first session is free.
          .panel-body
            %h2 I want to:
            %ul.list-unstyled
              %li
                = link_to "#", class: "panel objective-link trackEvent", data: {name: "Lose Weight", value: "lose-weight"} do
                  .panel-body
                    = image_tag("icon-scale.png")
                    %h4 Lose Weight
              %li
                = link_to "#", class: "panel objective-link trackEvent", data: {name: "Get Toned", value: "get-toned"} do
                  .panel-body
                    = image_tag("icon-tone.png")
                    %h4 Get Toned
              %li
                = link_to "#", class: "panel objective-link trackEvent", data: {name: "Get Stronger", value: "get-stronger"} do
                  .panel-body
                    = image_tag("icon-weights.png")
                    %h4 Get Stronger
              %li
                = link_to "#", class: "panel objective-link trackEvent", data: {name: "Finish a Race", value: "finish-race"} do
                  .panel-body
                    = image_tag("icon-run.png")
                    %h4 Finish a Race
      .slide.personalize
        .panel.lead-form
          .panel-heading
            = link_to "#", class: "prev-slide trackEvent", data: {name: "Back button on leadgen form"} do
              = image_tag("icon-signup-back.png")
            %h4
              Great! You want to
              %span
            %p Now tell us a little about yourself
          .panel-body
            .form-alerts
            %form#find-trainer-form{:role => "form"}
              %input{type: "hidden", id: "objective", name: "objective"}
              .row
                .col-md-6
                  .form-group
                    %label{:for => "name"} What's your name?
                    %input#name.form-control{placeholder: "First Last", type: "name", name: "name", required: "required"}
                    %span.glyphicon.glyphicon-ok.form-control-feedback
                .col-md-6
                  .form-group
                    %label{:for => "email"} What's your email address?
                    %input#email.form-control{placeholder: "Enter email", type: "email", name: "email", required: "required"}
                    %span.glyphicon.glyphicon-ok.form-control-feedback
              / .form-group
              /   %label{for: "price"} How much do you want to pay for this?
              /   .row
              /     .col-md-9.col-sm-9.col-xs-7
              /       %input#pricepoint{"data-slider-id" => "price-slider", "data-slider-max" => "200", "data-slider-min" => "20", "data-slider-step" => "5", "data-slider-value" => "80", type: "text", name: "pricepoint"}
              /     .col-md-3.col-sm-3.col-xs-5.no-padding-left
              /       .price-update.badge
              /         = raw("$<span class='price-input'>80</span>")
              /         per session
              /   %span.glyphicon.glyphicon-ok.form-control-feedback
              .row
                .col-md-6
                  .form-group
                    %label{:for => "location"} Where would you like to work out?
                    %select#location.form-control
                      %option{value: ""} Please select one
                      %option Castro District
                      %option Chinatown
                      %option Cole Valley
                      %option Financial District
                      %option Fisherman's Wharf
                      %option Haight-Ashbury
                      %option Hayes Valley
                      %option Japantown
                      %option Lower Haight
                      %option Marina
                      %option Mission District
                      %option Nob Hill
                      %option Noe Valley
                      %option North Beach
                      %option Pacific Heights
                      %option Panhandle
                      %option Potrero Hill
                      %option Presidio
                      %option Richmond
                      %option Russian Hill
                      %option Sea Cliff
                      %option Sixth Street
                      %option SOMA
                      %option Sunset
                      %option Tenderloin
                      %option Union Square
                      %option Upper Market
                    %span.glyphicon.glyphicon-ok.form-control-feedback
                .col-md-6
                  .form-group
                    %label{:for => "start-date"} When can you start?
                    .date-input
                      %input#startdate.datepicker.form-control{placeholder: "Click to select", type: "text", name: "startdate", required: "required"}
                      %span.glyphicon.glyphicon-calendar
                    %span.glyphicon.glyphicon-ok.form-control-feedback
              .row
                .col-md-12
                  .form-group
                    %label{:for => "activities"} What activities do you enjoy?
                    %input{type: "hidden", id: "activities", name: "activities"}
                    .activities
                      = link_to "Running", "#", class: "label label-default trackEvent", data: {name: "Clicked running"}
                      = link_to "Swimming", "#", class: "label label-default trackEvent", data: {name: "Clicked swimming"}
                      = link_to "Biking", "#", class: "label label-default trackEvent", data: {name: "Clicked biking"}
                      = link_to "Yoga", "#", class: "label label-default trackEvent", data: {name: "Clicked yoga"}
                      = link_to "Pilates", "#", class: "label label-default trackEvent", data: {name: "Clicked pilates"}
                      = link_to "Crossfit", "#", class: "label label-default trackEvent", data: {name: "Clicked crossfit"}
                      = link_to "Other", "#", class: "label label-default trackEvent", data: {name: "Clicked other"}

              %button.btn.btn-submit.btn-success.btn-lg.trackEvent{type: "submit", data: {name: "Submitted leadgen form"}} Find My Coach &raquo;
      .slide.finish
        .panel.lead-form
          .panel-body
            = image_tag("icon-checkmark-big.png")
            %h3 Sweet, we're on it!
            %p.lead
              We're hot on the search for your perfect trainer and can't wait for you to try out a <strong>free session</strong>. We will send you an email as soon as we've located them (usually within 24 hours).

app/views/home/index.html.haml
.header-cont
  = render partial: "shared/header"
  .overlay
  .leadgen
    .container
      .splash-cont
        .promo
          %h1
            %span
              Fitness Workouts
              At Your Startup
          %p.lead
            %span
              Promote a healthier, happier workplace
              with in-office workouts once a week.

          = link_to "Learn More", "#learn", class: "scroll-link btn btn-lg btn-primary btn-default"
.big-quote
  .container
    %blockquote
      "...medical costs fall by about
      %strong $3.27
      for every dollar spent on wellness programs..."
    %em
      Workplace Wellness Programs Can Generate Savings<br/>
      \- Harvard Health Affairs Journal, February 2010

.how-it-works#learn
  .container
    - if params[:type] == "request_info"
      .alert.alert-success.alert-dismissible{:role => "alert"}
        %button.close{"data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
          %span.sr-only Close
        %strong Thanks for reaching out!
        Someone will be in touch with you in the next 24 hours.
    %h2.title
      %span How It Works
    .row.feature
      .col-md-4.col-md-push-8
        = image_tag("icon-checklist.png", class: "icon")
      .col-md-8.col-md-pull-4
        %h3 1. Employees select this week's class
        %p.big The Mighty app allows your employees to vote on the group fitness class for the week. Classes include: Office Space Yoga, (re)Boot Camp, Passive Aggressive Pilates and many more.
    .row.feature
      .col-md-4
        = image_tag("icon-calendar.png", class: "icon")
      .col-md-8
        %h3 2. Sessions scheduled for each week
        %p.big We schedule the fitness sessions on your company's preferred day and time, and handle all logistics involved with setting up and paying for the trainer. 
    .row.feature
      .col-md-4.col-md-push-8
        = image_tag("icon-yoga.png", class: "icon")
      .col-md-8.col-md-pull-4
        %h3 3. Work out with your fitness instructor
        %p.big Enjoy your workout either indoors in your office or outdoors when it's nice. Your instructor will provide all equipment needed and fresh towels to boot!

.container
  .panel.panel-default#request-info
    .panel-heading
      %h3 Request Info
    .panel-body
      %p.lead
        %strong Mighty
        is paving the way for startup wellness programs. If you'd like to learn more about the services we offer, or how to enroll, please provide your contact information below.

        %form.form-inline{:role => "form", action: root_path, method: "GET"}
          %input{type: "hidden", name: "type", value: "request_info"}
          .form-group
            %label.sr-only{:for => "name"} Name
            %input#name.form-control{name: "name", :placeholder => "Name", :type => "text"}
          .form-group
            %label.sr-only{:for => "email"} Email
            %input#email.form-control{name: "email", :placeholder => "Email", :type => "email"}
          .form-group
            %label.sr-only{:for => "phone"} Phone Number
            %input#phone.form-control{name: "phone", :placeholder => "Phone Number", :type => "text"}
          %button.btn.btn-success{:type => "submit"} Submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mighty
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto:400,700", :rel => "stylesheet", :type => "text/css"}
    %link{:href => asset_url("favicon.ico"), :rel => "shortcut icon", :type => "image/x-icon"}
    %link{:href => asset_url("favicon.ico"), :rel => "icon", :type => "image/x-icon"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render partial: "shared/header"
    = yield
    = render partial: "shared/footer"

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-55777749-1', 'auto');
      ga('send', 'pageview');

app/views/layouts/home.html.haml
!!!
%html
  %head
    %title Mighty
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto:400,700", :rel => "stylesheet", :type => "text/css"}
    %link{:href => asset_url("favicon.ico"), :rel => "shortcut icon", :type => "image/x-icon"}
    %link{:href => asset_url("favicon.ico"), :rel => "icon", :type => "image/x-icon"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = yield
    = render partial: "shared/footer"

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-55777749-1', 'auto');
      ga('send', 'pageview');

app/views/lead_notifier/lead_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <center>
      <table cellpadding="0" cellspacing="0" height="100%" width="100%" style="border:none">
        <tbody>
          <tr>
            <td align="center" valign="top" width="100%">
              <table width="465" cellpadding="0" cellspacing="0">
                <tbody>
                  <tr>
                    <td align="left" valign="bottom" style="font-family:'Trebuchet MS','Helvetica Neue',Helvetica,Arial,sans-serif;padding:30px 0 0;font-stretch:normal;font-size:28px;line-height:45px;text-align:center;">Mighty</td>
                    <td align="right" valign="bottom" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;padding:30px 0px 18px;color:rgb(102,102,102);font-stretch:normal;font-size:14px;line-height:19px"><br></td>
                  </tr>
                </tbody>
              </table>
              <table width="465" cellpadding="0" cellspacing="0">
                <tbody>
                  <tr>
                    <td align="center" valign="top" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:rgb(102,102,102);font-stretch:normal;font-size:14px;line-height:19px">
                      <table cellpadding="0" cellspacing="0">
                        <tbody>
                          <tr>
                            <td align="left" height="10"></td>
                          </tr>
                        </tbody>
                      </table>
                      <table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:0px;line-height:1.5em;border:1px solid rgb(204,204,204);background:rgb(255,255,255)">
                        <tbody>
                          <tr>
                            <td align="left" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;padding:20px;font-stretch:normal;font-size:14px;line-height:19px">Hello <%= @lead.name %>,&nbsp;<br><br>Thanks for telling us about your personal training needs. Here's what to expect:&nbsp;<br><br><span style="font-weight:bold;font-stretch:normal;font-size:18px;line-height:10px;padding-right:2px">1.</span>&nbsp;Over the next 24 hours, we'll find a certified personal trainer based on your fitness goals and location.&nbsp;<br><br><span style="font-weight:bold;font-stretch:normal;font-size:18px;line-height:10px;padding-right:2px">2.</span>&nbsp;Mighty will reach out to you introducing your personal trainer and their background and qualifications. From there, you and your trainer can set up your first session. Remember, your first workout is on the house!&nbsp;<br><br>We're excited to introduce you to your personal trainer who will help you meet your fitness goals!&nbsp;<br><br>– The Mighty Team</td>
                          </tr>
                        </tbody>
                      </table>
                      <br>
                    </td>
                  </tr>
                </tbody>
              </table>
              <table cellpadding="0" cellspacing="0" width="100%" style="margin:0px;padding:0px">
                <tbody>
                  <tr>
                    <td align="center" style="padding:20px 0px;background:rgb(255,255,255)">
                      <table width="465" cellspacing="0" cellpadding="0">
                        <tbody>
                          <tr>
                            <td align="center" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;padding:0px 0px 15px;color:rgb(102,102,102);font-stretch:normal;font-size:14px;line-height:19px;width:464px">Mighty is always here to help</td>
                          </tr>
                        </tbody>
                      </table>
                      <table width="465" cellspacing="0" cellpadding="0">
                        <tbody>
                          <tr>
                            <td valign="top" align="left" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;width:155px;color:black;text-decoration:underline;font-stretch:normal;font-size:12px;line-height:17px"><br></td>
                            <td valign="top" align="left" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;width:155px;color:black;text-decoration:underline;text-align:center;font-stretch:normal;font-size:12px;line-height:17px"><a href="mailto:hi@mightyapp.co" style="color:rgb(102,102,102);text-align:left;font-stretch:normal" target="_blank">Email support</a><br></td>
                            <td valign="top" align="left" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;width:155px;color:black;text-decoration:underline;text-align:right;font-stretch:normal;font-size:12px;line-height:17px"><br></td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td align="center" style="padding:15px 0px;border-top-style:solid;border-top-width:1px;border-top-color:rgb(228,228,228);background:rgb(255,255,255)"></td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </tbody>
      </table>
    </center>
  </body>
</html>

app/views/lead_notifier/lead_email.text.erb
Hello <%= @lead.name %>,

Thanks for telling us about your personal training needs. Here's what to
expect:

1. Over the next 24 hours, we'll find a certified personal trainer based on
your fitness goals and location.

2. Mighty will reach out to you introducing your personal trainer and their
background and qualifications. From there, you and your trainer can set up
your first session. Remember, your first workout is on the house!

We're excited to introduce you to your personal trainer who will help you
meet your fitness goals!

- The Mighty Team
Mighty is always here to help
Email support <hi@mightyapp.co>

app/views/lead_notifier/request_info_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <center>
      <table cellpadding="0" cellspacing="0" height="100%" width="100%" style="border:none">
        <tbody>
          <tr>
            <td align="center" valign="top" width="100%">
              <table width="465" cellpadding="0" cellspacing="0">
                <tbody>
                  <tr>
                    <td align="left" valign="bottom" style="font-family:'Trebuchet MS','Helvetica Neue',Helvetica,Arial,sans-serif;padding:30px 0 0;font-stretch:normal;font-size:28px;line-height:45px;text-align:center;">Mighty</td>
                    <td align="right" valign="bottom" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;padding:30px 0px 18px;color:rgb(102,102,102);font-stretch:normal;font-size:14px;line-height:19px"><br></td>
                  </tr>
                </tbody>
              </table>
              <table width="465" cellpadding="0" cellspacing="0">
                <tbody>
                  <tr>
                    <td align="center" valign="top" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:rgb(102,102,102);font-stretch:normal;font-size:14px;line-height:19px">
                      <table cellpadding="0" cellspacing="0">
                        <tbody>
                          <tr>
                            <td align="left" height="10"></td>
                          </tr>
                        </tbody>
                      </table>
                      <table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin:0px;line-height:1.5em;border:1px solid rgb(204,204,204);background:rgb(255,255,255)">
                        <tbody>
                          <tr>
                            <td align="left" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;padding:20px;font-stretch:normal;font-size:14px;line-height:19px">Hello guys,&nbsp;<br><br>
                            You have a new lead:<br /><br />
                            <strong>Name:</strong> <%= @lead[:name] %> <br />
                            <strong>Email:</strong> <%= @lead[:email] %> <br />
                            <strong>Phone:</strong> <%= @lead[:phone] %> <br />
                            <br><br>– The Mighty Team</td>
                          </tr>
                        </tbody>
                      </table>
                      <br>
                    </td>
                  </tr>
                </tbody>
              </table>
              <table cellpadding="0" cellspacing="0" width="100%" style="margin:0px;padding:0px">
                <tbody>
                  <tr>
                    <td align="center" style="padding:20px 0px;background:rgb(255,255,255)">
                      <table width="465" cellspacing="0" cellpadding="0">
                        <tbody>
                          <tr>
                            <td align="center" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;padding:0px 0px 15px;color:rgb(102,102,102);font-stretch:normal;font-size:14px;line-height:19px;width:464px">Mighty is always here to help</td>
                          </tr>
                        </tbody>
                      </table>
                      <table width="465" cellspacing="0" cellpadding="0">
                        <tbody>
                          <tr>
                            <td valign="top" align="left" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;width:155px;color:black;text-decoration:underline;font-stretch:normal;font-size:12px;line-height:17px"><br></td>
                            <td valign="top" align="left" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;width:155px;color:black;text-decoration:underline;text-align:center;font-stretch:normal;font-size:12px;line-height:17px"><a href="mailto:hi@mightyapp.co" style="color:rgb(102,102,102);text-align:left;font-stretch:normal" target="_blank">Email support</a><br></td>
                            <td valign="top" align="left" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;width:155px;color:black;text-decoration:underline;text-align:right;font-stretch:normal;font-size:12px;line-height:17px"><br></td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td align="center" style="padding:15px 0px;border-top-style:solid;border-top-width:1px;border-top-color:rgb(228,228,228);background:rgb(255,255,255)"></td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </tbody>
      </table>
    </center>
  </body>
</html>

app/views/lead_notifier/request_info_email.text.erb
Hello guys,

You have a new lead:

Name: <%= @lead[:name] %>
Email: <%= @lead[:email] %>
Phone: <%= @lead[:phone] %>

- The Mighty Team
Mighty is always here to help
Email support <hi@mightyapp.co>

app/views/leads/_form.html.haml
= form_for(@lead, role: "form") do |f|
  - if @lead.errors.any?
    #error_explanation
      %h2
        = pluralize(@lead.errors.count, "error")
        prohibited this lead from being saved:
      %ul
        - @lead.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :objective
    = f.text_field :objective, class: "form-control"
  .form-group
    = f.label :location
    = f.text_field :location, class: "form-control"
  .form-group
    = f.label :activities
    = f.text_field :activities, class: "form-control"
  .form-group
    = f.label :pricepoint
    = f.text_field :pricepoint, class: "form-control"
  .form-group
    = f.label :email
    = f.text_field :email, class: "form-control"
  .form-group
    = f.label :startdate
    = f.text_field :startdate, class: "form-control"
  .form-group
    = f.submit 'Save', class: "btn btn-large btn-primary"

app/views/leads/edit.html.haml
.container.simple-page
  .panel
    .panel-heading
      = link_to raw('Show Lead'), @lead, class: "btn btn-sm btn-success pull-right"
      %h1 Edit Lead
    .panel-body
      = render 'form'
      = link_to raw('&laquo Back'), leads_path, class: "btn btn-sm btn-link"

app/views/leads/index.html.haml
.container.simple-page
  .panel
    .panel-heading
      %h1 Listing leads
    .panel-body
      %table.table
        %thead
          %tr
            %th Name
            %th Objective
            %th Location
            %th Activities
            %th Pricepoint
            %th Email
            %th Startdate
            %th{:colspan => "3"}
        %tbody
          - @leads.each do |lead|
            %tr
              %td= lead.name
              %td= lead.objective
              %td= lead.location
              %td= lead.activities
              %td= lead.pricepoint
              %td= lead.email
              %td= lead.startdate
              %td= link_to 'Show', lead
              %td= link_to 'Edit', edit_lead_path(lead)
              %td= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' }
      %br
        = link_to 'New Lead', new_lead_path, class: "btn btn-lg btn-default"

app/views/leads/new.html.haml
.container.simple-page
  .panel
    .panel-heading
      %h1 New Lead
    .panel-body
      = render 'form'
      = link_to raw('&laquo Back'), leads_path, class: "btn btn-sm btn-link"

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lead.name %>
</p>

<p>
  <strong>Objective:</strong>
  <%= @lead.objective %>
</p>

<p>
  <strong>Activities:</strong>
  <%= @lead.activities %>
</p>

<p>
  <strong>Pricepoint:</strong>
  <%= @lead.pricepoint %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @lead.startdate %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>

app/views/pages/concierge.html.haml
.leadgen
  .container
    .splash-cont
      .promo
        %h1
          Certified Trainers,
          %br.phone-spacer
          Affordable Rates
        %p.lead
          Find an expert personal trainer
          %br.phone-spacer
          that will help you reach your goals.
      = render partial: "shared/slider_trainer"

= render partial: "shared/how_it_works"
= render partial: "shared/testimonials"

app/views/pages/sports.html.haml
.leadgen
  .container
    .splash-cont
      .promo
        %h1
          Sports Lessons
          %br.phone-spacer
          In Small Groups
        %p.lead
          Learn from experienced athletes
          %br.phone-spacer
          with fun and motivated peers.
      = render partial: "shared/slider_sports"

= render partial: "shared/how_it_works"
= render partial: "shared/testimonials"

app/views/pages/test.html.haml
%h3 Test page

app/views/shared/_footer.html.haml
.footer
  .container
    .row
      .col-md-6
        \&copy;
        = succeed "," do
          %strong Mighty
        All Rights Reserved.
      .col-md-6.text-right
        %ul.list-inline
          %li
            %a{:href => "mailto: hi@mightyapp.co"} Contact Us